name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Set up Docker Build
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/polnilnica-backend:latest .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}polnilnica-backend/myapp:latest

    - name: Log out from Docker Hub
      run: docker logout
